### PR TITLE
Remove cookies

### PR DESCRIPTION
**Pull request by brianmcmichael**
This is a redesign of the user selection process that doesn't use cookies, submitted as a potential resolution to #84.

Instead of cookies, which were used on the client and server side, this branch uses the browser's localStorage feature to save the selected key, it then passes it to the server as a query param.

localStorage browser support:
http://caniuse.com/#feat=namevalue-storage

### CODE REVIEW

**Comment by brianmcmichael** [comment]
The initializer for this in `config/initializers/filter.rb` is currently unversioned, so if/when this gets updated on the system, the initializer will need a refresh.

**Comment by ericfranz** [comment]
So since you pass the filter id now as a query param when fetching records, which filter id to use and how that is stored is completely isolated to two lines:

```javascript
var filter_id = localStorage.getItem("jobfilter") || "<%= Filter.default_id %>";
```

and

```javascript
<label id="<%= filter.filter_id %>" class="btn btn-primary" onclick="localStorage.setItem('jobfilter', '<%= filter.filter_id %>'); window.location.reload();" >
```

It seems like you could make `setFilterId(id)` and `getFilterId()` functions that use localStorage if it is available (feature checking via modernizr, for example) or use cookies as a backup. Safari <10 doesn't support this and we haven't increased our browser restrictions yet.

That said, in regards to `window.location.reload()` I thought that if you had a datatables table that was configured to use ajax, you could trigger a reload of the datatables without reloading the entire page. If you did that, would you actually be able to continue to use cookies because the reload could accept an argument, forcing to use the correct filter_id value, regardless of whether the corresponding cookie had been updated yet. User experience might be better too because you would just be reloading the table contents instead of the entire page.

**Comment by nickjer** [comment]
> Safari <10 doesn't support this

Are you talking about `localStorage`? As Safari 4+ supports this feature.

**Comment by ericfranz** [comment]
Ha http://caniuse.com/#feat=namevalue-storage threw me off

**Comment by brianmcmichael** [comment]
There are some problems with continuing to use cookies, namely, the `cookies.js` is out of date, and the new one provided by MDN has a `GPL` license. 

I experimented with some other cookie storage helpers because it's tricky to properly set and get cookie paths across browsers using the default apis. Localstorage is a pretty simple solution that seems to work everywhere.

I think modifying this app for ajax reloading is a worthy goal fit for a separate issue/PR.

**Comment by brianmcmichael** [comment]
@ericfranz can this be merged?

**Pull request merged**
